DOMAIN = "nrfclaw"

SERVICE_UUID = "4e52a800-0000-10a7-d24b-6a3244619a47"
RX_UUID = "4e52a801-0000-10a7-d24b-6a3244619a47"
TX_UUID = "4e52a802-0000-10a7-d24b-6a3244619a47"

APP_SERVICE_UUID = SERVICE_UUID
APP_RX_UUID = RX_UUID
APP_TX_UUID = TX_UUID

CONF_ACCESS_KEY = "access_key"
CONF_MODE = "mode"
CONF_POLL_INTERVAL = "poll_interval"

MODE_DIRECT = "direct"
MODE_BRIDGE = "bridge"
# Existing B7.5 config entries predate CONF_MODE and must retain bridge behavior.
LEGACY_DEFAULT_MODE = MODE_BRIDGE
DEFAULT_DIRECT_POLL_INTERVAL = 60
MIN_DIRECT_POLL_INTERVAL = 10
MAX_DIRECT_POLL_INTERVAL = 3600

# B7.6c: expensive identity/capability discovery is infrequent in Direct mode.
DIRECT_STATIC_REFRESH_INTERVAL = 3600
DIRECT_BATTERY_REFRESH_INTERVAL = 300

# NDP v1 stable opcodes used by the HA read-only path.
NDP_INFO = 32
NDP_CAPS = 33
NDP_STATUS = 34
# B7.6b one-shot Application low-power disconnect hint.
NDP_BLE_DISCONNECT_HINT = 92
NDP_DIRECT_SENSOR_CONTROL = 94
NDP_DIRECT_EVENT_SENSITIVITY = 95
NDP_DIRECT_HALL_CONTROL = 96
NDP_DIRECT_SEMANTIC_STATE = 97

SEMCAP_VOLUME = 0x0601
SEMCAP_VOLUME_US_GALLON = 0x0606
NDP_BOARD_INFO = 35
NDP_BOARD_MEMORY = 36
NDP_BOARD_RESET = 37
NDP_SENSOR_READ = 52
NDP_AUTH_BEGIN = 64
NDP_AUTH_FINISH = 65
NDP_AUTH_LOGOUT = 66
NDP_ACCESS_STATUS = 67
NDP_VIB_AUTO_START = 74
NDP_VIB_AUTO_STOP = 75
NDP_VIB_AUTO_STATUS = 76
NDP_VIB_AUTO_CONFIG = 77
NDP_VIB_AUTO_RESET = 79

NDP_ACCESS_PUBLIC = 0
NDP_ACCESS_CONTROL = 1
NDP_ACCESS_PROVISION = 2

NDP_OK = 0
NDP_BUSY = 4
NDP_UNAUTHORIZED = 5

# Native capability IDs. NDP_CAPS bit N-1 corresponds to capability N.
CAP_GPIO = 1
CAP_BATTERY = 2
CAP_DS18B20 = 3
CAP_ACCEL = 4
CAP_LORA = 5
CAP_BLE_APP = 6
CAP_RTC = 7
CAP_HALL = 8
CAP_STATE = 9
CAP_SERIAL = 10
CAP_TRACKING = 11
CAP_VIB_HEALTH = 12
CAP_VIB_AUTO = 13
CAP_TEMPERATURE = 14

SENSOR_BATTERY = 1
SENSOR_HALL = 2
SENSOR_ACCEL_XYZ = 3
SENSOR_DS18B20 = 4
SENSOR_ACCEL_METRICS = 5
SENSOR_TEMPERATURE = 6

ACCEL_EVENT_OFF = 0
ACCEL_EVENT_MOTION = 1
ACCEL_EVENT_TAP = 2
ACCEL_EVENT_FALL = 3
ACCEL_EVENT_WALK = 4
ACCEL_EVENT_VIBRATION = 5

EVENT_SENSITIVITY_LOW = 0
EVENT_SENSITIVITY_NORMAL = 1
EVENT_SENSITIVITY_HIGH = 2

HALL_MODE_OFF = 0
HALL_MODE_SINGLE = 1
HALL_MODE_QUADRATURE = 2

BOARD_NAMES = {
    1: "NINASENSE",
    2: "PCA10040",
    3: "HALFMOON",
}

PLATFORMS = ["sensor"]

# Persistent NinaLink HA runtime
NDP_NINALINK_BRIDGE = 0x5A
